
version: "1.0"
services:
  gpu-test:
    image: undefined
    expose:
      - port: undefined
        as: 80
        to:
          - global: true
    env:
      - TEST=test
profiles:
  name: hello-world
  mode: provider
  duration: undefinedh
  tier:
    - community
  compute:
    gpu-test:
      resources:
        cpu:
          units: 1
        memory:
          size: 20Gi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: undefined
  placement:
    undefined:
      attributes:
        region: undefined
      pricing:
        gpu-test:
          token: USDT
          amount: NaN
deployment:
  gpu-test:
    undefined:
      profile: gpu-test
      count: 1
