
version: "1.0"
services:
  gpu-test:
    image: jenkins/jenkins:lts
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - TEST=test
profiles:
  name: hello-world
  mode: provider
  duration: 1h
  tier:
    - community
  compute:
    gpu-test:
      resources:
        cpu:
          units: 1
        memory:
          size: 20Gi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx6000-ada
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        gpu-test:
          token: ETH
          amount: 1.85
deployment:
  gpu-test:
    westcoast:
      profile: gpu-test
      count: 1
