
version: "1.0"

services:
  py-cuda:
    image: undefined
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
    env:
      - JUPYTER_TOKEN=sentient
profiles:
  name: py-cuda
  duration: 3456h
  mode: provider
  tier:
    - community
  compute:
    py-cuda:
      resources:
        cpu:
          units: 1
        memory:
          size: 16Gi
        storage:
          - size: 200Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: t1000
  placement:
    westcoast:
      attributes:
        region: us-central
      pricing:
        py-cuda:
          token: CST
          amount: 8.64

deployment:
  py-cuda:
    westcoast:
      profile: py-cuda
      count: 1
  