
version: "1.0"
services:
  gpu-test:
    image: gpu-test-image:latest
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - TEST=test
profiles:
  name: hello-world
  mode: provider
  duration: 24h
  tier:
    - community
  compute:
    gpu-test:
      resources:
        cpu:
          units: 1
        memory:
          size: 20Gi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: Tesla T4
  placement:
    us-west-1:
      attributes:
        region: us-west-1
      pricing:
        gpu-test:
          token: USDT
          amount: 51
deployment:
  gpu-test:
    us-west-1:
      profile: gpu-test
      count: 1
